-- BASE DE DATOS DATOSALUMNOS
-- 1º DAW
-- 26-01-2023
-- WALTER MARTIN LOPES
-- -------------------------------------------------------
CREATE DATABASE DDL2;
USE DDL2;

-- 1 CREACION DE TABLAS
CREATE TABLE EMPLEADOS(
DNI CHAR(9),
NOMBRE VARCHAR(10),
APELLIDO1 VARCHAR(15),
APELLIDO2 VARCHAR(15),
DIRECC1 VARCHAR(25),
DIRECC2 VARCHAR(20),
CIUDAD VARCHAR(20),
PROVINCIA VARCHAR(20),
COD_POSTAL CHAR(5),
SEXO CHAR(1),
FECHA_NAC DATE);

CREATE TABLE ESTUDIOS(
EMPLEADO_DNI CHAR(9),
UNIVERSIDAD INT,
AÑO INT,
GRADO VARCHAR(3),
ESPECIALIDAD VARCHAR(20));

CREATE TABLE UNIVERSIDADES(
COD_UNIV INT,
NOMBRE_UNIV VARCHAR(25),
CIUDAD VARCHAR(20),
MUNICIPIO VARCHAR(2),
COD_POSTAL CHAR(5));

CREATE TABLE TRABAJOS(
COD_TRABAJO INT,
NOMBRE_TRAB VARCHAR(20),
SALARIO_MIN DECIMAL(10,2),
SALARIO_MAX DECIMAL(10,2));

CREATE TABLE DEPARTAMENTOS(
COD_DPTO INT,
NOMBRE_DPTO VARCHAR(30),
DPTO_PADRE INT,
PRESUPUESTO DECIMAL(10,2),
PRES_ACTUAL DECIMAL(10,2));

CREATE TABLE HISTORIAL_LABORAL(
DNI_EMPLEADO CHAR(9),
COD_TRABAJO INT,
FECHA_INICIO DATE,
FECHA_FIN DATE,
COD_DPTO INT,
DNI_SUPERVISOR INT);

CREATE TABLE HISTORIAL_SALARIAL(
DNI_EMPLEADO CHAR(9),
SALARIO DECIMAL(10,2),
FECHA_COMIENZO DATE,
FECHA_FIN DATE);