CREATE DATABASE EJEMPLOS_PROCEDIMIENTOS;
USE EJEMPLOS_PROCEDIMIENTOS;

-- EJEMPLO 1
DELIMITER //
DROP PROCEDURE IF EXISTS VAR_EJEMPLO1//
CREATE PROCEDURE VAR_EJEMPLO1()
BEGIN
DECLARE VARIABLE1 INT;
DECLARE VARIABLE2 VARCHAR(20);
SET VARIABLE1=25;
SET VARIABLE2 = "ESTO ES UNA PRUEBA";
SELECT CONCAT_WS('******',VARIABLE1,VARIABLE2) AS RESULTADO;
END //

DELIMITER ;

CALL VAR_EJEMPLO1();

-- EJEMPLO 2
CREATE TABLE ALUMNOS (
ID INT PRIMARY KEY,
ALUMNO VARCHAR(20));

INSERT INTO ALUMNOS VALUES
(1,'ALUMNO1'),
(2,'ALUMNO2'),
(3,'ALUMNO3'),
(4,'ALUMNO4'),
(5,'ALUMNO5');

DELIMITER //
DROP PROCEDURE IF EXISTS VAR_EJEMPLO2//
CREATE PROCEDURE VAR_EJEMPLO2()
BEGIN
	DECLARE V_1 INT;
    DECLARE V_2 VARCHAR(20);
    
    SELECT ID,ALUMNO INTO V_1,V_2 FROM ALUMNOS
    WHERE ID=4;
    SELECT V_1,V_2;
END; //
DELIMITER ;

CALL VAR_EJEMPLO2;