-- CREACIÓN DE LA BD SUMINISTROS

CREATE DATABASE SUMINISTROS;

-- CONEXION A LA BD
USE SUMINISTROS;

-- CREACIÓN DE TABLAS

CREATE TABLE CLIENTE
(
DNI VARCHAR(9) PRIMARY KEY,
NOMBRE VARCHAR(25),
APELLIDO VARCHAR(30),
FECHA_NAC INT,
TFNO VARCHAR(9)
);

CREATE TABLE PRODUCTO
(
CODIGO VARCHAR(15) PRIMARY KEY,
NOMBRE VARCHAR(25),
PRECIO DECIMAL(5,4)
);

CREATE TABLE PROVEDOR
(
NIF VARCHAR(9) PRIMARY KEY,
NOMBRE VARCHAR(20),
DIRECCION VARCHAR(25)
);

ALTER TABLE CLIENTE
MODIFY FECHA_NAC DATE;

ALTER TABLE PRODUCTO
MODIFY CODIGO INT;

CREATE TABLE COMPRAS
(
DNI_CLIENTE VARCHAR(9),
CODIGO_PRODUCTO INT,
CONSTRAINT COM_PK PRIMARY KEY (DNI_CLIENTE,CODIGO_PRODUCTO),
CONSTRAINT CLI_FK FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT PRO_FK FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO)
ON UPDATE CASCADE ON DELETE CASCADE
);
